---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: shopwave
  labels:
    app: cart-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: cart-service
        version: v1
    spec:
      containers:
        - name: cart-service
          image: 491325670828.dkr.ecr.us-east-1.amazonaws.com/shopwave/cart-service:8582656
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:8000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: shopwave
  labels:
    app: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cart-service-hpa
  namespace: shopwave
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cart-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

